# Generated by Django 2.2.5 on 2019-09-09 16:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contributor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(5)])),
                ('author', models.CharField(max_length=200)),
                ('editor', models.CharField(max_length=200)),
                ('reviewer', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('country', models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(5)])),
            ],
        ),
    ]
